version: '2.3'

services:
  # SERVICE: cli
  cli:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: lagoon/cli.dockerfile
    image: &cli-image adv-task-cli 
    labels:
      lagoon.type: cli
      lagoon.name: cli
      lagoon.persistent.name: nginx
    volumes:
      - ./:/app:delegated
    volumes_from: 
      - container:amazeeio-ssh-agent

networks:
  amazeeio-network:
    external: true
