version: '2.3'

services:
  # SERVICE: report
  report:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: drupclean_report.dockerfile

  # SERVICE: nuke
  nuke:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: drupclean_nuke.dockerfile

networks:
  amazeeio-network:
    external: true
