version: '2.3'

services:
  # SERVICE: drupclean
  drupclean:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: lagoon/drupclean.dockerfile
    image: &cli-image drupclean
    labels:
      lagoon.type: cli
      lagoon.name: drupclean
      lagoon.persistent: /app/files
      lagoon.persistent.name: nginx
    volumes:
      - ./:/app:delegated
    volumes_from: 
      - container:amazeeio-ssh-agent

networks:
  amazeeio-network:
    external: true
