version: '2.3'

services:
  # SERVICE: report
  report:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: drupclean_report.dockerfile

  # SERVICE: nuke
  nuke:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: drupclean_nuke.dockerfile
  
  # SERVICE: nuke
  cli:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: drupclean_cli.dockerfile
    volumes:
      - ./cli:/app
    volumes_from: 
      - container:amazeeio-ssh-agent 

networks:
  amazeeio-network:
    external: true
